name: Node CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master

    - name: Install App
      run: make install

    - name: Run Linter
      run: make lint

    - name: Run Unit Tests
      run: make tests
